[infrastructure.nodes.rukkileib]
cores = [[1, 2, 3]]
iface = "test"

[topology.defaults.links]
latency = "5ms"
metric = 1
mtu = 9000
bw = "100gbit"

[topology.defaults.nodes.sysctls]
"net.ipv6.conf.default.forwarding" = "1"
"net.ipv6.conf.all.forwarding" = "1"
"net.ipv6.conf.default.keep_addr_on_down" = "1"

[topology.defaults.nodes.templates]
"ospf.cfg" = "/tmp/{{node}}.ospf.cfg"
"holod.toml" = "/tmp/{{node}}.holod.toml"

[topology.defaults.nodes]
exec = [
  "~/holo/target/debug/holo-cli --file /tmp/{{node}}.ospf.cfg"
]

[[topology.defaults.nodes.pinned]]
cmd = "~/holo/target/debug/holod -c /tmp/holod.toml &"
environ.IO_QUIC_CORE_ID = "{{core_1}}"
  
[topology.nodes.r0]
rid = "0.0.0.1"
addrs.lo = ["fc00:1::"]

[topology.nodes.r1]
rid = "0.0.0.2"
addrs.lo = ["fc00:1::1"]

[topology.nodes.r2]
rid = "0.0.0.3"
addrs.lo = ["fc00:1::2"]
quic.ca = "test"

[topology.nodes.r3]
rid = "0.0.0.4"
addrs.lo = ["fc00:1::3"]

[topology.nodes.r4]
rid = "0.0.0.5"
addrs.lo = ["fc00:1::4"]

[topology]
links = [
  {endpoints = ["r0:eth0", "r1:eth0"]},
  {endpoints = ["r0:eth1", "r2:eth0"]}
]

