[project]
name = "dune"
dependencies = ["pytoml", "pyyaml", "mpf @ git+https://github.com/mpiraux/mpf.git"]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "dune_mpf._dune_mpf"
name = "dune"
