name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    # - uses: dtolnay/rust-toolchain@nightly
    - name: Set toolchain version
      run: rustup override set 1.88
    - name: Build crate
      run: cargo build
    - name: Run tests
      run: cargo test -p dune-core -p dune-cli -p dune-mpf
