name: Build

on:
  push:
    branches: [ "rust" ]
  pull_request:
    branches: [ "rust" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - name: Build crate
      run: cargo build
    - name: Run tests
      run: cargo test -p dune-core -p dune-cli -p dune-mpf
