[package]
name = "dune-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }

dune-core = { path = "../dune-core" }
dune-mpf = { path = "../dune-mpf" }

[lints]
workspace = true
